@startuml


' ---- Layout & Stil ----
hide empty methods

 
' ---- Legende ----
legend right
<<RichType>>: Stark typisierte Primitive
<<ValueObject>>: Value Objects
<<entity>>: Persistente Entität
<<unique>>: Eindeutige Einschränkung auf Spaltenebene
<<nn>>: Not null
endlegend

' ===================== Packages =====================

package "Shared\n(Value Objects)" as P_Shared #EEF6FF {
 
  class Email << (R,#FFEECC) RichType >> {
    +Value: string <<nn>>
  }
 
  class Phone << (R,#FFEECC) RichType >> {
    +Value: string <<nn>>
  }
 
  class Address << (V,#CCEEFF) ValueObject >> {
    +street: string <<nn>>
    +zip: TimeOnly <<nn>>
    +city: string <<nn>>
    +country: string <<nn>>
  }
  
  class OpeningHours << (V,#CCEEFF) ValueObject >> {
    +OpenTime: TimeOnly <<nn>>
    +CloseTime: TimeOnly <<nn>>
  }
  
  enum UserRole {
    Admin
    Customer
    Restaurant_Owner
    Guest
  }
}

package "Customer" as P_Customer #FFF5E6 {

    abstract class Customer <<entity>> {
        +Role: UserRole <<nn>>
    }
    
    class RegisteredCustomer <<entity>> {
       +FirstName: string <<nn>>
       +LastName: string <<nn>>
       +Email: Email <<nn>>
       +Phone: Phone
       +Address: Address <<nn>>
    }
    
    class AnonymousCustomer <<entity>> {
    }
}

package "Restaurant_Owner" as P_Restaurant_Owner #8AA8A1 {
     class RestarauntOwner <<entity>> {
        +Role: UserRole <<nn>>
        +CompanyName: string <<nn>>
        +CompanyAddress: Address <<nn>>
        +VatId: string <<nn>>
        +Phone: Phone <<nn>>
        +Email: Email <<nn>>
        +FirstName : string <<nn>>
        +LastName : string <<nn>>
     }
 }


package "Cart" as P_Cart #EAF8EA {

    class Cart <<entity>> {
        +Customer: Customer <<nn>>
        +Resturant: Restaurant <<nn>>
        +CartItems: List<CartItem> <<nn>>
    }
    
    class CartItem <<entity>> {
        +MenuItem: MenuItem <<nn>>
        +Cart: Cart <<nn>>
        +Quantity: int <<nn>>
        +Comment: string
    }
}


package "Restaurant" as P_Restaurant #D3C0D2 {

   class Restaurant <<entity>> {
        +RestarauntOwner: RestarauntOwner <<nn>>
        +Name: string <<nn>>
        +Address: Address <<nn>>
        +Phone: Phone <<nn>>
        +OpeningHours: OpeningHours <<nn>>
    }

    class MenuItem <<entity>> {
        +Restaruant: Restaurant <<nn>>
        +Name: string <<nn>>
        +Description: string <<nn>>
        +Price: decimal <<nn>>
    }
}

package "Order" as P_Order #FFF0FF {

    class Order <<entity>> {
        +OrderedAt: DateTime <<nn>>
        +Customer: RegisteredCustomer <<nn>>
        +Resturant: Restaurant <<nn>>
        +OrderItems: List<OrderItem>
    }
    
    class OrderItem <<entity>> {
        +Order: Order <<nn>>
        +MenuItem: MenuItem <<nn>>
        +Quantity: int <<nn>>
        +Price: decimal <<nn>>
    }
}

' ===================== Beziehungen =====================

Customer <|-- RegisteredCustomer
Customer <|-- AnonymousCustomer

Restaurant "1" <-- "*" MenuItem
Restaurant "*" --> "1" RestarauntOwner

Cart "0..1" --> "1" Customer
Cart "*" --> "1" Restaurant
Cart "1" <-- "*" CartItem

CartItem "*" --> "1" MenuItem

Order "1" <-- "*" OrderItem
Order "1" --> "1" RegisteredCustomer
Order "1" --> "1" Restaurant



@enduml