POST localhost:5000/api/customers
Content-Type: application/json

{
    "firstName": "",
    "lastName": "fischer",
    "email": "helenefischer2@gmx.at",
    "password": "12345678",
    "address": {
        "street": "Hauptstraße 1",
        "zip": "12345",
        "city": "München",
        "country": "Deutschland"
    }
  }